### PR TITLE
2018 ICO Refactoring

### PR DESCRIPTION
**Pull request by CooperStansbury**
Summary of changes below:

## Content Changes
1. Align representations across multiple ontologies.
     - Simplify representations to support greater interoperability and multiple contexts of use at the application level.
    - Align ICO's representation of 'permissions' with d-acts 'document act'. 
    - Import and support DUO 'consent codes'.
    - Improve natural language definitions for most ICO classes.

1. Expand representation of the regulatory background.
    - Refactored the Common Rule Ontology utilizing the same design philosophy as ICO.
    - Add new classes of information content entities 

1. Expand representation of informed consent forms and their constituent parts.
    - Add new information content entities to represent informed consent forms and other regulatory documents related to informed consent.

## Technical Changes
1. Simplify ICO import structure.
1. Add a reproducible release process for managing ontology releases moving forward. 
1. Restructure repository to make development easier.
1. Add lots of documentation. 

@yongqunh we will need to update the OBO yaml file to point to `/ico.owl`. The purls currently resolve to 'src/ontology/ico-merged.owl`.  Please respond with to-dos and requested changes.

### CODE REVIEW

**Comment by yongqunh** [comment]
Got it. Will look over all these soon. 
Thanks, Oliver

**Comment by yongqunh** [comment]
Cooper, the ico owl file you provided appears to be a merged file. it's good to have the merged file. I have some specific questions in removed terms and added terms.   
However, before I ask those questions, I would like to ensure that we will keep our separate unmerged files including the unmerged ico.owl file and each imported files. The reason is that the imported files may change often. For example, we may add new imports from many ontologies such as OBI and OBIB. Our imports may include updated OBI or OBIB terms. We don't want to do it manually later. We can do it ontologically using Ontofox. This is why we have our strategy of always keeping the individual imports files and editing these files as well as the unmerged ico.owl file. Then for release, we can generate the merged file by merging the separate files.  
With this strategy, we need to get the original imports files and Ontofox input files. 
Do you have those original files? If yes, could you add them back to your folder. 
See the OHMI project GitHub website for reference: https://github.com/OHMI-ontology/OHMI .

**Comment by CooperStansbury** [comment]
> Cooper, the ico owl file you provided appears to be a merged file. it's good to have the merged file. I have some specific questions in removed terms and added terms.
> However, before I ask those questions, I would like to ensure that we will keep our separate unmerged files including the unmerged ico.owl file and each imported files. The reason is that the imported files may change often. For example, we may add new imports from many ontologies such as OBI and OBIB. Our imports may include updated OBI or OBIB terms. We don't want to do it manually later. We can do it ontologically using Ontofox. This is why we have our strategy of always keeping the individual imports files and editing these files as well as the unmerged ico.owl file. Then for release, we can generate the merged file by merging the separate files.
> With this strategy, we need to get the original imports files and Ontofox input files.
> Do you have those original files? If yes, could you add them back to your folder.
> See the OHMI project GitHub website for reference: https://github.com/OHMI-ontology/OHMI .

Hi @yongqunh, unmerged 'in-development' file can be found here: [`src/ontology/ico-edit.owl`](https://raw.githubusercontent.com/ICO-Scrub-Team/ICO/master/src/ontology/ico-edit.owl). The merged file is built from the development file `src/ontology/ico-edit.owl` in order to manage upstream import changes with each release. 

Does this help?

**Comment by yongqunh** [comment]
Good. The unmerged files in [`src/ontology/ico-edit.owl`](https://raw.githubusercontent.com/ICO-Scrub-Team/ICO/master/src/ontology/ico-edit.owl) appear to include: 
duo
d-acts
ro/temporal-intervals.owl
ro/core.owl

However, from comparison with the original unmerged file, we have:
BFO
IAO
OAE
OBI
OGMS
RO
d-acts
--
So DUO is new, which is good. 
d-acts and RO also exist in the original version. Are there any updates among these versions? 
Also, the BFO, IAO, OAE, OBI, and OGMS imports are not found.

**Comment by yongqunh** [comment]
Also, as seen in the ico-edit.owl file:
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/duo/releases/2019-01-07/duo.owl"/>
        <owl:imports rdf:resource="http://ontofox.hegroup.org/a7gex0gq.owl"/>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/iao/d-acts.owl"/>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/ro/temporal-intervals.owl"/>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/ro/core.owl"/>
It appears that you are importing all contents of d-acts.owl, duo, ro/temporal-intervals.owl and ro/core.owl. The importing of all the contents of these ontologies makes ICO quite big. We typically do not do it. We only import those terms that ICO really needs by using OntoFox method. In addition, I am not sure what the ontofox output (http://ontofox.hegroup.org/a7gex0gq.owl) is about. The label needs to be updated.  
Please let me know if you need help. We can set up another meeting soon to go over these.

**Comment by yongqunh** [comment]
Answers for your action items:
*  For BFO and IAO, if we don't use all BFO and IAO terms, we need to specify what terms imported, which can be included in local imports file. We can also periodically edit and updates. Local files are easy to monitor and update. 
* The same for D-acts and RO-core terms. Are all the D-acts and RO-core terms related to ICO? We only need to import what we need, and discard what we don't need. 

Question: for your import slims with terms from OBIB, OAE, and OGMS, do you maintain an input files? If you use Ontofox, do you have an Ontofox input file? What if we want to add or change our list of terms from these ontologies? Such an Ontofox input file is critical to check and update such a list.

**Comment by CooperStansbury** [comment]
@yongqunh Does this mean that we need to curate local versions of all ontology terms that ICO uses? This seems too manual to be effective long-term. 

I would prefer to import IAO, BFO, D-Acts, RO, and DUO in their entirety via `owl:Imports` and use robot to resolve to the most current version each time we release ICO. I think that this reduces the need to manage 10 extra files (OntoFox Inputs + Import slims). If this is not suitable to you I will add local versions of each of the above and adjust the `catalog-v001.xml` on the next commit. 

6eb883d adds OntoFox input specs,  BFO + IAO explicitly to ICO `owl:imports` statements, and adds local copies of D-Acts and RO_core.

**Comment by yongqunh** [comment]
I think that we should import only those terms related to ICO from IAO, BFO, D-Acts, RO, and DUO, instead of their entirety. In the end, ICO is not a combination of IAO, BFO, D-Acts, RO, and DUO and plus ICO terms.  If needed, we can generate one Ontofox input file that includes terms from all the other ontologies, so we don't need to have so many extra files. However, we do need to have such an extra input file and selected terms (instead of their entire imports).

**Comment by CooperStansbury** [comment]
@yongqunh bccb821 adds local versions for all imports and commits `catalog-v001.xml` in order to help Protege users resolve the purls to local files. I think it makes most sense to have each import file be separate, just to make things clear, so for now each import has it's own local, slim version unless we make use of the entire ontology (d-acts, duo, and both RO ontologies). 

Let me know if this works for you. 

Thanks,

**Comment by yongqunh** [comment]
OK. Good to make slim import file for each ontology separately.

**Comment by CooperStansbury** [comment]
@yongqunh, 63df5d4 should fix the catalog and prevent Protege from overwriting it each time it is opened. The line below seems to have been the culprit..

```xml
<group id="Folder Repository, directory=, recursive=true, Auto-Update=true, version=2" prefer="public" xml:base="">
```

**Comment by fjmanion** [comment]
Just for my edification is that line in the catalogue.xml file or somewhere else. 

Frank J. Manion

**Comment by CooperStansbury** [comment]
@fjmanion correct, when Protege auto-creates the `catalog-v001.xml` file it includes that line, which allows Protege to keep writing over that file.

**Comment by CooperStansbury** [comment]
@yongqunh 

80f8f36 does a number of things, per our offline discussions:

1. Added a curator note to each of the re-instated classes: 'This class is under group discussion as of 03/26/2019.'
1. Add you as a 'definition editor' to each of the re-instated classes.
1. Re-ran release process so that `./ico.owl` is current with these changes.

**Pull request merged**
